version: '3.8'

services:
  cassandra:
    image: cassandra:5.0
    container_name: cassandra
    environment:
      CASSANDRA_USERNAME: cassandra
      CASSANDRA_PASSWORD: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./init.cql:/docker-entrypoint-initdb.d/init.cql
    networks:
      - daily-note-network
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  daily-note-network:
    driver: bridge
