spring.application.name=note-app
server.port=9091
# Use AWS Secrets Manager for sensitive values
# Import secrets as a property source (store secrets in AWS Secrets Manager)
spring.config.import=aws-secretsmanager:daily_note_secret_manager
# Set the AWS region (replace with your region)
spring.cloud.aws.region.static=ap-south-1
spring.cloud.aws.secretsmanager.region=ap-south-1
# Database Configuration (non-sensitive)
# Node IP addresses or hostnames (comma-separated)
# Cassandra
spring.cassandra.contact-points=${spring.cassandra.contact-points}
spring.cassandra.port=${spring.cassandra.port}
spring.cassandra.keyspace-name=${spring.cassandra.keyspace-name}
spring.cassandra.local-datacenter=${spring.cassandra.local-datacenter}
# Instructs Spring to create the keyspace if it is missing
# Credentials are expected to come from AWS Secrets Manager
spring.cassandra.username=${spring.cassandra.username:}
spring.cassandra.password=${spring.cassandra.password:}
spring.cassandra.connection.connect-timeout=5s
spring.cassandra.connection.init-query-timeout=5s
logging.level.org.springframework.data.cassandra.core.cql.CqlTemplate=DEBUG
logging.level.org.springframework.data.cassandra.core=DEBUG
logging.level.com.datastax.oss.driver=INFO
# S3 Bucket Configuration
# Credentials loaded from AWS Secrets Manager
aws.s3.bucket-name=${aws.s3.bucket-name}
aws.s3.access-key=${aws.s3.access-key:}
aws.s3.secret-key=${aws.s3.secret-key:}
aws.s3.region=${aws.s3.region}
# Replace 'com.example.noteapp.entity' with your actual package structure
spring.cassandra.entity-base-packages=com.daily_notes.notes.entity
#DYnamoDB Log COnfig
logging.level.software.amazon.awssdk=DEBUG
logging.level.software.amazon.awssdk.request=DEBUG
logging.level.software.amazon.awssdk.services.dynamodb=DEBUG
logging.level.software.amazon.awssdk.enhanced.dynamodb=DEBUG
logging.level.io.awspring.cloud.dynamodb=DEBUG
logging.level.software.amazon.awssdk.http=DEBUG


# Base application logging
logging.level.root=INFO
logging.level.com.daily_notes=DEBUG

# Spring Web Logging
logging.level.org.springframework.web=INFO

logging.level.org.apache.http.wire=DEBUG
logging.level.software.amazon.awssdk.http.stateless=DEBUG