spring.application.name=notes
server.port=9091
# Database Configuration
# Node IP addresses or hostnames (comma-separated)
# Cassandra
spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.keyspace-name=my_keyspace
spring.cassandra.local-datacenter=datacenter1

spring.cassandra.username=cassandra
spring.cassandra.password=cassandra

spring.cassandra.schema-action=create-if-not-exists

spring.cassandra.connection.connect-timeout=5s
spring.cassandra.connection.init-query-timeout=5s

logging.level.org.springframework.data.cassandra.core.cql.CqlTemplate=DEBUG
logging.level.org.springframework.data.cassandra.core=DEBUG
logging.level.com.datastax.oss.driver=INFO